// Code generated by scripts/api/main.go. DO NOT EDIT.
/*
 * BigAnimal
 *
 * BigAnimal REST API v2 <br /><br /> Please visit [API v2 Changelog page](/api/docs/v2migration.html) for information about migrating from API v1.
 *
 * API version: 17.28.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiv2

import "encoding/json"

type EventsBody struct {
	EndAt    string          `json:"endAt"`
	Order    *string         `json:"order,omitempty"`
	Paging   *EventsPaging   `json:"paging"`
	Resource *EventsResource `json:"resource,omitempty"`
	StartAt  string          `json:"startAt"`
	User     *EventsUser     `json:"user,omitempty"`
}

func (m EventsBody) String() string {
	data, _ := json.MarshalIndent(m, "", "\t")
	return string(data)
}
