/*
BigAnimal

BigAnimal REST API v2 <br /><br /> Please visit [API v2 Changelog page](/api/docs/v2migration.html) for information about migrating from API v1. 

API version: 2.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetUsage200Response struct for GetUsage200Response
type GetUsage200Response struct {
	Data Usage `json:"data"`
}

// NewGetUsage200Response instantiates a new GetUsage200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetUsage200Response(data Usage) *GetUsage200Response {
	this := GetUsage200Response{}
	this.Data = data
	return &this
}

// NewGetUsage200ResponseWithDefaults instantiates a new GetUsage200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetUsage200ResponseWithDefaults() *GetUsage200Response {
	this := GetUsage200Response{}
	return &this
}

// GetData returns the Data field value
func (o *GetUsage200Response) GetData() Usage {
	if o == nil {
		var ret Usage
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetUsage200Response) GetDataOk() (*Usage, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GetUsage200Response) SetData(v Usage) {
	o.Data = v
}

func (o GetUsage200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableGetUsage200Response struct {
	value *GetUsage200Response
	isSet bool
}

func (v NullableGetUsage200Response) Get() *GetUsage200Response {
	return v.value
}

func (v *NullableGetUsage200Response) Set(val *GetUsage200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetUsage200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetUsage200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetUsage200Response(val *GetUsage200Response) *NullableGetUsage200Response {
	return &NullableGetUsage200Response{value: val, isSet: true}
}

func (v NullableGetUsage200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetUsage200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


