/*
BigAnimal

BigAnimal REST API v2 <br /><br /> Please visit [API v2 Changelog page](/api/docs/v2migration.html) for information about migrating from API v1. 

API version: 2.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetAccountNews200Response struct for GetAccountNews200Response
type GetAccountNews200Response struct {
	Data []AccountNews `json:"data"`
}

// NewGetAccountNews200Response instantiates a new GetAccountNews200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAccountNews200Response(data []AccountNews) *GetAccountNews200Response {
	this := GetAccountNews200Response{}
	this.Data = data
	return &this
}

// NewGetAccountNews200ResponseWithDefaults instantiates a new GetAccountNews200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAccountNews200ResponseWithDefaults() *GetAccountNews200Response {
	this := GetAccountNews200Response{}
	return &this
}

// GetData returns the Data field value
func (o *GetAccountNews200Response) GetData() []AccountNews {
	if o == nil {
		var ret []AccountNews
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetAccountNews200Response) GetDataOk() ([]AccountNews, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *GetAccountNews200Response) SetData(v []AccountNews) {
	o.Data = v
}

func (o GetAccountNews200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableGetAccountNews200Response struct {
	value *GetAccountNews200Response
	isSet bool
}

func (v NullableGetAccountNews200Response) Get() *GetAccountNews200Response {
	return v.value
}

func (v *NullableGetAccountNews200Response) Set(val *GetAccountNews200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAccountNews200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAccountNews200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAccountNews200Response(val *GetAccountNews200Response) *NullableGetAccountNews200Response {
	return &NullableGetAccountNews200Response{value: val, isSet: true}
}

func (v NullableGetAccountNews200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAccountNews200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


