/*
BigAnimal

BigAnimal REST API v2 <br /><br /> Please visit [API v2 Changelog page](/api/docs/v2migration.html) for information about migrating from API v1. 

API version: 2.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// Billing struct for Billing
type Billing struct {
	ClusterCharges []ClusterCharge `json:"clusterCharges"`
	TotalVcpuHours float32 `json:"totalVcpuHours"`
}

// NewBilling instantiates a new Billing object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBilling(clusterCharges []ClusterCharge, totalVcpuHours float32) *Billing {
	this := Billing{}
	this.ClusterCharges = clusterCharges
	this.TotalVcpuHours = totalVcpuHours
	return &this
}

// NewBillingWithDefaults instantiates a new Billing object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBillingWithDefaults() *Billing {
	this := Billing{}
	return &this
}

// GetClusterCharges returns the ClusterCharges field value
func (o *Billing) GetClusterCharges() []ClusterCharge {
	if o == nil {
		var ret []ClusterCharge
		return ret
	}

	return o.ClusterCharges
}

// GetClusterChargesOk returns a tuple with the ClusterCharges field value
// and a boolean to check if the value has been set.
func (o *Billing) GetClusterChargesOk() ([]ClusterCharge, bool) {
	if o == nil {
		return nil, false
	}
	return o.ClusterCharges, true
}

// SetClusterCharges sets field value
func (o *Billing) SetClusterCharges(v []ClusterCharge) {
	o.ClusterCharges = v
}

// GetTotalVcpuHours returns the TotalVcpuHours field value
func (o *Billing) GetTotalVcpuHours() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.TotalVcpuHours
}

// GetTotalVcpuHoursOk returns a tuple with the TotalVcpuHours field value
// and a boolean to check if the value has been set.
func (o *Billing) GetTotalVcpuHoursOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalVcpuHours, true
}

// SetTotalVcpuHours sets field value
func (o *Billing) SetTotalVcpuHours(v float32) {
	o.TotalVcpuHours = v
}

func (o Billing) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["clusterCharges"] = o.ClusterCharges
	}
	if true {
		toSerialize["totalVcpuHours"] = o.TotalVcpuHours
	}
	return json.Marshal(toSerialize)
}

type NullableBilling struct {
	value *Billing
	isSet bool
}

func (v NullableBilling) Get() *Billing {
	return v.value
}

func (v *NullableBilling) Set(val *Billing) {
	v.value = val
	v.isSet = true
}

func (v NullableBilling) IsSet() bool {
	return v.isSet
}

func (v *NullableBilling) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBilling(val *Billing) *NullableBilling {
	return &NullableBilling{value: val, isSet: true}
}

func (v NullableBilling) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBilling) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


