/*
BigAnimal

BigAnimal REST API v2 <br /><br /> Please visit [API v2 Changelog page](/api/docs/v2migration.html) for information about migrating from API v1. 

API version: 2.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetClusterArchitectures200Response struct for GetClusterArchitectures200Response
type GetClusterArchitectures200Response struct {
	Data []ClusterArchitecture `json:"data"`
}

// NewGetClusterArchitectures200Response instantiates a new GetClusterArchitectures200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetClusterArchitectures200Response(data []ClusterArchitecture) *GetClusterArchitectures200Response {
	this := GetClusterArchitectures200Response{}
	this.Data = data
	return &this
}

// NewGetClusterArchitectures200ResponseWithDefaults instantiates a new GetClusterArchitectures200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetClusterArchitectures200ResponseWithDefaults() *GetClusterArchitectures200Response {
	this := GetClusterArchitectures200Response{}
	return &this
}

// GetData returns the Data field value
func (o *GetClusterArchitectures200Response) GetData() []ClusterArchitecture {
	if o == nil {
		var ret []ClusterArchitecture
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetClusterArchitectures200Response) GetDataOk() ([]ClusterArchitecture, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *GetClusterArchitectures200Response) SetData(v []ClusterArchitecture) {
	o.Data = v
}

func (o GetClusterArchitectures200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableGetClusterArchitectures200Response struct {
	value *GetClusterArchitectures200Response
	isSet bool
}

func (v NullableGetClusterArchitectures200Response) Get() *GetClusterArchitectures200Response {
	return v.value
}

func (v *NullableGetClusterArchitectures200Response) Set(val *GetClusterArchitectures200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetClusterArchitectures200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetClusterArchitectures200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetClusterArchitectures200Response(val *GetClusterArchitectures200Response) *NullableGetClusterArchitectures200Response {
	return &NullableGetClusterArchitectures200Response{value: val, isSet: true}
}

func (v NullableGetClusterArchitectures200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetClusterArchitectures200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


