/*
BigAnimal

BigAnimal REST API v2 <br /><br /> Please visit [API v2 Changelog page](/api/docs/v2migration.html) for information about migrating from API v1. 

API version: 2.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CreatePgConfigTemplate200Response struct for CreatePgConfigTemplate200Response
type CreatePgConfigTemplate200Response struct {
	Data CreatePgConfigTemplate200ResponseData `json:"data"`
}

// NewCreatePgConfigTemplate200Response instantiates a new CreatePgConfigTemplate200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatePgConfigTemplate200Response(data CreatePgConfigTemplate200ResponseData) *CreatePgConfigTemplate200Response {
	this := CreatePgConfigTemplate200Response{}
	this.Data = data
	return &this
}

// NewCreatePgConfigTemplate200ResponseWithDefaults instantiates a new CreatePgConfigTemplate200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatePgConfigTemplate200ResponseWithDefaults() *CreatePgConfigTemplate200Response {
	this := CreatePgConfigTemplate200Response{}
	return &this
}

// GetData returns the Data field value
func (o *CreatePgConfigTemplate200Response) GetData() CreatePgConfigTemplate200ResponseData {
	if o == nil {
		var ret CreatePgConfigTemplate200ResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CreatePgConfigTemplate200Response) GetDataOk() (*CreatePgConfigTemplate200ResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *CreatePgConfigTemplate200Response) SetData(v CreatePgConfigTemplate200ResponseData) {
	o.Data = v
}

func (o CreatePgConfigTemplate200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableCreatePgConfigTemplate200Response struct {
	value *CreatePgConfigTemplate200Response
	isSet bool
}

func (v NullableCreatePgConfigTemplate200Response) Get() *CreatePgConfigTemplate200Response {
	return v.value
}

func (v *NullableCreatePgConfigTemplate200Response) Set(val *CreatePgConfigTemplate200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatePgConfigTemplate200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatePgConfigTemplate200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatePgConfigTemplate200Response(val *CreatePgConfigTemplate200Response) *NullableCreatePgConfigTemplate200Response {
	return &NullableCreatePgConfigTemplate200Response{value: val, isSet: true}
}

func (v NullableCreatePgConfigTemplate200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatePgConfigTemplate200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


