/*
BigAnimal

BigAnimal REST API v2 <br /><br /> Please visit [API v2 Changelog page](/api/docs/v2migration.html) for information about migrating from API v1. 

API version: 2.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// PgConfigTemplate struct for PgConfigTemplate
type PgConfigTemplate struct {
	PgConfigTemplateId string `json:"pgConfigTemplateId"`
	PgTypeId string `json:"pgTypeId"`
	PgTypeName *string `json:"pgTypeName,omitempty"`
	PgVersionId string `json:"pgVersionId"`
	PgVersionName *string `json:"pgVersionName,omitempty"`
	TemplateName string `json:"templateName"`
	TemplateDescription *string `json:"templateDescription,omitempty"`
}

// NewPgConfigTemplate instantiates a new PgConfigTemplate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPgConfigTemplate(pgConfigTemplateId string, pgTypeId string, pgVersionId string, templateName string) *PgConfigTemplate {
	this := PgConfigTemplate{}
	this.PgConfigTemplateId = pgConfigTemplateId
	this.PgTypeId = pgTypeId
	this.PgVersionId = pgVersionId
	this.TemplateName = templateName
	return &this
}

// NewPgConfigTemplateWithDefaults instantiates a new PgConfigTemplate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPgConfigTemplateWithDefaults() *PgConfigTemplate {
	this := PgConfigTemplate{}
	return &this
}

// GetPgConfigTemplateId returns the PgConfigTemplateId field value
func (o *PgConfigTemplate) GetPgConfigTemplateId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PgConfigTemplateId
}

// GetPgConfigTemplateIdOk returns a tuple with the PgConfigTemplateId field value
// and a boolean to check if the value has been set.
func (o *PgConfigTemplate) GetPgConfigTemplateIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PgConfigTemplateId, true
}

// SetPgConfigTemplateId sets field value
func (o *PgConfigTemplate) SetPgConfigTemplateId(v string) {
	o.PgConfigTemplateId = v
}

// GetPgTypeId returns the PgTypeId field value
func (o *PgConfigTemplate) GetPgTypeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PgTypeId
}

// GetPgTypeIdOk returns a tuple with the PgTypeId field value
// and a boolean to check if the value has been set.
func (o *PgConfigTemplate) GetPgTypeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PgTypeId, true
}

// SetPgTypeId sets field value
func (o *PgConfigTemplate) SetPgTypeId(v string) {
	o.PgTypeId = v
}

// GetPgTypeName returns the PgTypeName field value if set, zero value otherwise.
func (o *PgConfigTemplate) GetPgTypeName() string {
	if o == nil || o.PgTypeName == nil {
		var ret string
		return ret
	}
	return *o.PgTypeName
}

// GetPgTypeNameOk returns a tuple with the PgTypeName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PgConfigTemplate) GetPgTypeNameOk() (*string, bool) {
	if o == nil || o.PgTypeName == nil {
		return nil, false
	}
	return o.PgTypeName, true
}

// HasPgTypeName returns a boolean if a field has been set.
func (o *PgConfigTemplate) HasPgTypeName() bool {
	if o != nil && o.PgTypeName != nil {
		return true
	}

	return false
}

// SetPgTypeName gets a reference to the given string and assigns it to the PgTypeName field.
func (o *PgConfigTemplate) SetPgTypeName(v string) {
	o.PgTypeName = &v
}

// GetPgVersionId returns the PgVersionId field value
func (o *PgConfigTemplate) GetPgVersionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PgVersionId
}

// GetPgVersionIdOk returns a tuple with the PgVersionId field value
// and a boolean to check if the value has been set.
func (o *PgConfigTemplate) GetPgVersionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PgVersionId, true
}

// SetPgVersionId sets field value
func (o *PgConfigTemplate) SetPgVersionId(v string) {
	o.PgVersionId = v
}

// GetPgVersionName returns the PgVersionName field value if set, zero value otherwise.
func (o *PgConfigTemplate) GetPgVersionName() string {
	if o == nil || o.PgVersionName == nil {
		var ret string
		return ret
	}
	return *o.PgVersionName
}

// GetPgVersionNameOk returns a tuple with the PgVersionName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PgConfigTemplate) GetPgVersionNameOk() (*string, bool) {
	if o == nil || o.PgVersionName == nil {
		return nil, false
	}
	return o.PgVersionName, true
}

// HasPgVersionName returns a boolean if a field has been set.
func (o *PgConfigTemplate) HasPgVersionName() bool {
	if o != nil && o.PgVersionName != nil {
		return true
	}

	return false
}

// SetPgVersionName gets a reference to the given string and assigns it to the PgVersionName field.
func (o *PgConfigTemplate) SetPgVersionName(v string) {
	o.PgVersionName = &v
}

// GetTemplateName returns the TemplateName field value
func (o *PgConfigTemplate) GetTemplateName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TemplateName
}

// GetTemplateNameOk returns a tuple with the TemplateName field value
// and a boolean to check if the value has been set.
func (o *PgConfigTemplate) GetTemplateNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TemplateName, true
}

// SetTemplateName sets field value
func (o *PgConfigTemplate) SetTemplateName(v string) {
	o.TemplateName = v
}

// GetTemplateDescription returns the TemplateDescription field value if set, zero value otherwise.
func (o *PgConfigTemplate) GetTemplateDescription() string {
	if o == nil || o.TemplateDescription == nil {
		var ret string
		return ret
	}
	return *o.TemplateDescription
}

// GetTemplateDescriptionOk returns a tuple with the TemplateDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PgConfigTemplate) GetTemplateDescriptionOk() (*string, bool) {
	if o == nil || o.TemplateDescription == nil {
		return nil, false
	}
	return o.TemplateDescription, true
}

// HasTemplateDescription returns a boolean if a field has been set.
func (o *PgConfigTemplate) HasTemplateDescription() bool {
	if o != nil && o.TemplateDescription != nil {
		return true
	}

	return false
}

// SetTemplateDescription gets a reference to the given string and assigns it to the TemplateDescription field.
func (o *PgConfigTemplate) SetTemplateDescription(v string) {
	o.TemplateDescription = &v
}

func (o PgConfigTemplate) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["pgConfigTemplateId"] = o.PgConfigTemplateId
	}
	if true {
		toSerialize["pgTypeId"] = o.PgTypeId
	}
	if o.PgTypeName != nil {
		toSerialize["pgTypeName"] = o.PgTypeName
	}
	if true {
		toSerialize["pgVersionId"] = o.PgVersionId
	}
	if o.PgVersionName != nil {
		toSerialize["pgVersionName"] = o.PgVersionName
	}
	if true {
		toSerialize["templateName"] = o.TemplateName
	}
	if o.TemplateDescription != nil {
		toSerialize["templateDescription"] = o.TemplateDescription
	}
	return json.Marshal(toSerialize)
}

type NullablePgConfigTemplate struct {
	value *PgConfigTemplate
	isSet bool
}

func (v NullablePgConfigTemplate) Get() *PgConfigTemplate {
	return v.value
}

func (v *NullablePgConfigTemplate) Set(val *PgConfigTemplate) {
	v.value = val
	v.isSet = true
}

func (v NullablePgConfigTemplate) IsSet() bool {
	return v.isSet
}

func (v *NullablePgConfigTemplate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePgConfigTemplate(val *PgConfigTemplate) *NullablePgConfigTemplate {
	return &NullablePgConfigTemplate{value: val, isSet: true}
}

func (v NullablePgConfigTemplate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePgConfigTemplate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


