/*
BigAnimal

BigAnimal REST API v2 <br /><br /> Please visit [API v2 Changelog page](/api/docs/v2migration.html) for information about migrating from API v1. 

API version: 2.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CreateClusterPgVersion struct for CreateClusterPgVersion
type CreateClusterPgVersion struct {
	PgVersionId string `json:"pgVersionId"`
}

// NewCreateClusterPgVersion instantiates a new CreateClusterPgVersion object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateClusterPgVersion(pgVersionId string) *CreateClusterPgVersion {
	this := CreateClusterPgVersion{}
	this.PgVersionId = pgVersionId
	return &this
}

// NewCreateClusterPgVersionWithDefaults instantiates a new CreateClusterPgVersion object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateClusterPgVersionWithDefaults() *CreateClusterPgVersion {
	this := CreateClusterPgVersion{}
	return &this
}

// GetPgVersionId returns the PgVersionId field value
func (o *CreateClusterPgVersion) GetPgVersionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PgVersionId
}

// GetPgVersionIdOk returns a tuple with the PgVersionId field value
// and a boolean to check if the value has been set.
func (o *CreateClusterPgVersion) GetPgVersionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PgVersionId, true
}

// SetPgVersionId sets field value
func (o *CreateClusterPgVersion) SetPgVersionId(v string) {
	o.PgVersionId = v
}

func (o CreateClusterPgVersion) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["pgVersionId"] = o.PgVersionId
	}
	return json.Marshal(toSerialize)
}

type NullableCreateClusterPgVersion struct {
	value *CreateClusterPgVersion
	isSet bool
}

func (v NullableCreateClusterPgVersion) Get() *CreateClusterPgVersion {
	return v.value
}

func (v *NullableCreateClusterPgVersion) Set(val *CreateClusterPgVersion) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateClusterPgVersion) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateClusterPgVersion) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateClusterPgVersion(val *CreateClusterPgVersion) *NullableCreateClusterPgVersion {
	return &NullableCreateClusterPgVersion{value: val, isSet: true}
}

func (v NullableCreateClusterPgVersion) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateClusterPgVersion) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


