/*
BigAnimal

BigAnimal REST API v2 <br /><br /> Please visit [API v2 Changelog page](/api/docs/v2migration.html) for information about migrating from API v1. 

API version: 2.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetConnectionList200Response struct for GetConnectionList200Response
type GetConnectionList200Response struct {
	Id *string `json:"id,omitempty"`
	SubscriptionId *string `json:"subscriptionId,omitempty"`
	BrokerConnectionId *string `json:"brokerConnectionId,omitempty"`
	BrokerConnectionName *string `json:"brokerConnectionName,omitempty"`
	Strategy *string `json:"strategy,omitempty"`
	BrokerConnOptions *GetConnectionList200ResponseBrokerConnOptions `json:"brokerConnOptions,omitempty"`
	BrokerConfigInfo *GetConnectionList200ResponseBrokerConfigInfo `json:"brokerConfigInfo,omitempty"`
	Validated *bool `json:"validated,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetConnectionList200Response GetConnectionList200Response

// NewGetConnectionList200Response instantiates a new GetConnectionList200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetConnectionList200Response() *GetConnectionList200Response {
	this := GetConnectionList200Response{}
	return &this
}

// NewGetConnectionList200ResponseWithDefaults instantiates a new GetConnectionList200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetConnectionList200ResponseWithDefaults() *GetConnectionList200Response {
	this := GetConnectionList200Response{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetConnectionList200Response) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetConnectionList200Response) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetConnectionList200Response) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *GetConnectionList200Response) SetId(v string) {
	o.Id = &v
}

// GetSubscriptionId returns the SubscriptionId field value if set, zero value otherwise.
func (o *GetConnectionList200Response) GetSubscriptionId() string {
	if o == nil || o.SubscriptionId == nil {
		var ret string
		return ret
	}
	return *o.SubscriptionId
}

// GetSubscriptionIdOk returns a tuple with the SubscriptionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetConnectionList200Response) GetSubscriptionIdOk() (*string, bool) {
	if o == nil || o.SubscriptionId == nil {
		return nil, false
	}
	return o.SubscriptionId, true
}

// HasSubscriptionId returns a boolean if a field has been set.
func (o *GetConnectionList200Response) HasSubscriptionId() bool {
	if o != nil && o.SubscriptionId != nil {
		return true
	}

	return false
}

// SetSubscriptionId gets a reference to the given string and assigns it to the SubscriptionId field.
func (o *GetConnectionList200Response) SetSubscriptionId(v string) {
	o.SubscriptionId = &v
}

// GetBrokerConnectionId returns the BrokerConnectionId field value if set, zero value otherwise.
func (o *GetConnectionList200Response) GetBrokerConnectionId() string {
	if o == nil || o.BrokerConnectionId == nil {
		var ret string
		return ret
	}
	return *o.BrokerConnectionId
}

// GetBrokerConnectionIdOk returns a tuple with the BrokerConnectionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetConnectionList200Response) GetBrokerConnectionIdOk() (*string, bool) {
	if o == nil || o.BrokerConnectionId == nil {
		return nil, false
	}
	return o.BrokerConnectionId, true
}

// HasBrokerConnectionId returns a boolean if a field has been set.
func (o *GetConnectionList200Response) HasBrokerConnectionId() bool {
	if o != nil && o.BrokerConnectionId != nil {
		return true
	}

	return false
}

// SetBrokerConnectionId gets a reference to the given string and assigns it to the BrokerConnectionId field.
func (o *GetConnectionList200Response) SetBrokerConnectionId(v string) {
	o.BrokerConnectionId = &v
}

// GetBrokerConnectionName returns the BrokerConnectionName field value if set, zero value otherwise.
func (o *GetConnectionList200Response) GetBrokerConnectionName() string {
	if o == nil || o.BrokerConnectionName == nil {
		var ret string
		return ret
	}
	return *o.BrokerConnectionName
}

// GetBrokerConnectionNameOk returns a tuple with the BrokerConnectionName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetConnectionList200Response) GetBrokerConnectionNameOk() (*string, bool) {
	if o == nil || o.BrokerConnectionName == nil {
		return nil, false
	}
	return o.BrokerConnectionName, true
}

// HasBrokerConnectionName returns a boolean if a field has been set.
func (o *GetConnectionList200Response) HasBrokerConnectionName() bool {
	if o != nil && o.BrokerConnectionName != nil {
		return true
	}

	return false
}

// SetBrokerConnectionName gets a reference to the given string and assigns it to the BrokerConnectionName field.
func (o *GetConnectionList200Response) SetBrokerConnectionName(v string) {
	o.BrokerConnectionName = &v
}

// GetStrategy returns the Strategy field value if set, zero value otherwise.
func (o *GetConnectionList200Response) GetStrategy() string {
	if o == nil || o.Strategy == nil {
		var ret string
		return ret
	}
	return *o.Strategy
}

// GetStrategyOk returns a tuple with the Strategy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetConnectionList200Response) GetStrategyOk() (*string, bool) {
	if o == nil || o.Strategy == nil {
		return nil, false
	}
	return o.Strategy, true
}

// HasStrategy returns a boolean if a field has been set.
func (o *GetConnectionList200Response) HasStrategy() bool {
	if o != nil && o.Strategy != nil {
		return true
	}

	return false
}

// SetStrategy gets a reference to the given string and assigns it to the Strategy field.
func (o *GetConnectionList200Response) SetStrategy(v string) {
	o.Strategy = &v
}

// GetBrokerConnOptions returns the BrokerConnOptions field value if set, zero value otherwise.
func (o *GetConnectionList200Response) GetBrokerConnOptions() GetConnectionList200ResponseBrokerConnOptions {
	if o == nil || o.BrokerConnOptions == nil {
		var ret GetConnectionList200ResponseBrokerConnOptions
		return ret
	}
	return *o.BrokerConnOptions
}

// GetBrokerConnOptionsOk returns a tuple with the BrokerConnOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetConnectionList200Response) GetBrokerConnOptionsOk() (*GetConnectionList200ResponseBrokerConnOptions, bool) {
	if o == nil || o.BrokerConnOptions == nil {
		return nil, false
	}
	return o.BrokerConnOptions, true
}

// HasBrokerConnOptions returns a boolean if a field has been set.
func (o *GetConnectionList200Response) HasBrokerConnOptions() bool {
	if o != nil && o.BrokerConnOptions != nil {
		return true
	}

	return false
}

// SetBrokerConnOptions gets a reference to the given GetConnectionList200ResponseBrokerConnOptions and assigns it to the BrokerConnOptions field.
func (o *GetConnectionList200Response) SetBrokerConnOptions(v GetConnectionList200ResponseBrokerConnOptions) {
	o.BrokerConnOptions = &v
}

// GetBrokerConfigInfo returns the BrokerConfigInfo field value if set, zero value otherwise.
func (o *GetConnectionList200Response) GetBrokerConfigInfo() GetConnectionList200ResponseBrokerConfigInfo {
	if o == nil || o.BrokerConfigInfo == nil {
		var ret GetConnectionList200ResponseBrokerConfigInfo
		return ret
	}
	return *o.BrokerConfigInfo
}

// GetBrokerConfigInfoOk returns a tuple with the BrokerConfigInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetConnectionList200Response) GetBrokerConfigInfoOk() (*GetConnectionList200ResponseBrokerConfigInfo, bool) {
	if o == nil || o.BrokerConfigInfo == nil {
		return nil, false
	}
	return o.BrokerConfigInfo, true
}

// HasBrokerConfigInfo returns a boolean if a field has been set.
func (o *GetConnectionList200Response) HasBrokerConfigInfo() bool {
	if o != nil && o.BrokerConfigInfo != nil {
		return true
	}

	return false
}

// SetBrokerConfigInfo gets a reference to the given GetConnectionList200ResponseBrokerConfigInfo and assigns it to the BrokerConfigInfo field.
func (o *GetConnectionList200Response) SetBrokerConfigInfo(v GetConnectionList200ResponseBrokerConfigInfo) {
	o.BrokerConfigInfo = &v
}

// GetValidated returns the Validated field value if set, zero value otherwise.
func (o *GetConnectionList200Response) GetValidated() bool {
	if o == nil || o.Validated == nil {
		var ret bool
		return ret
	}
	return *o.Validated
}

// GetValidatedOk returns a tuple with the Validated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetConnectionList200Response) GetValidatedOk() (*bool, bool) {
	if o == nil || o.Validated == nil {
		return nil, false
	}
	return o.Validated, true
}

// HasValidated returns a boolean if a field has been set.
func (o *GetConnectionList200Response) HasValidated() bool {
	if o != nil && o.Validated != nil {
		return true
	}

	return false
}

// SetValidated gets a reference to the given bool and assigns it to the Validated field.
func (o *GetConnectionList200Response) SetValidated(v bool) {
	o.Validated = &v
}

func (o GetConnectionList200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.SubscriptionId != nil {
		toSerialize["subscriptionId"] = o.SubscriptionId
	}
	if o.BrokerConnectionId != nil {
		toSerialize["brokerConnectionId"] = o.BrokerConnectionId
	}
	if o.BrokerConnectionName != nil {
		toSerialize["brokerConnectionName"] = o.BrokerConnectionName
	}
	if o.Strategy != nil {
		toSerialize["strategy"] = o.Strategy
	}
	if o.BrokerConnOptions != nil {
		toSerialize["brokerConnOptions"] = o.BrokerConnOptions
	}
	if o.BrokerConfigInfo != nil {
		toSerialize["brokerConfigInfo"] = o.BrokerConfigInfo
	}
	if o.Validated != nil {
		toSerialize["validated"] = o.Validated
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *GetConnectionList200Response) UnmarshalJSON(bytes []byte) (err error) {
	varGetConnectionList200Response := _GetConnectionList200Response{}

	if err = json.Unmarshal(bytes, &varGetConnectionList200Response); err == nil {
		*o = GetConnectionList200Response(varGetConnectionList200Response)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "subscriptionId")
		delete(additionalProperties, "brokerConnectionId")
		delete(additionalProperties, "brokerConnectionName")
		delete(additionalProperties, "strategy")
		delete(additionalProperties, "brokerConnOptions")
		delete(additionalProperties, "brokerConfigInfo")
		delete(additionalProperties, "validated")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetConnectionList200Response struct {
	value *GetConnectionList200Response
	isSet bool
}

func (v NullableGetConnectionList200Response) Get() *GetConnectionList200Response {
	return v.value
}

func (v *NullableGetConnectionList200Response) Set(val *GetConnectionList200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetConnectionList200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetConnectionList200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetConnectionList200Response(val *GetConnectionList200Response) *NullableGetConnectionList200Response {
	return &NullableGetConnectionList200Response{value: val, isSet: true}
}

func (v NullableGetConnectionList200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetConnectionList200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


