/*
BigAnimal

BigAnimal REST API v2 <br /><br /> Please visit [API v2 Changelog page](/api/docs/v2migration.html) for information about migrating from API v1. 

API version: 2.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetClusterConnection200Response struct for GetClusterConnection200Response
type GetClusterConnection200Response struct {
	Data ClusterConnection `json:"data"`
}

// NewGetClusterConnection200Response instantiates a new GetClusterConnection200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetClusterConnection200Response(data ClusterConnection) *GetClusterConnection200Response {
	this := GetClusterConnection200Response{}
	this.Data = data
	return &this
}

// NewGetClusterConnection200ResponseWithDefaults instantiates a new GetClusterConnection200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetClusterConnection200ResponseWithDefaults() *GetClusterConnection200Response {
	this := GetClusterConnection200Response{}
	return &this
}

// GetData returns the Data field value
func (o *GetClusterConnection200Response) GetData() ClusterConnection {
	if o == nil {
		var ret ClusterConnection
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetClusterConnection200Response) GetDataOk() (*ClusterConnection, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GetClusterConnection200Response) SetData(v ClusterConnection) {
	o.Data = v
}

func (o GetClusterConnection200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableGetClusterConnection200Response struct {
	value *GetClusterConnection200Response
	isSet bool
}

func (v NullableGetClusterConnection200Response) Get() *GetClusterConnection200Response {
	return v.value
}

func (v *NullableGetClusterConnection200Response) Set(val *GetClusterConnection200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetClusterConnection200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetClusterConnection200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetClusterConnection200Response(val *GetClusterConnection200Response) *NullableGetClusterConnection200Response {
	return &NullableGetClusterConnection200Response{value: val, isSet: true}
}

func (v NullableGetClusterConnection200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetClusterConnection200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


