/*
BigAnimal

BigAnimal REST API v2 <br /><br /> Please visit [API v2 Changelog page](/api/docs/v2migration.html) for information about migrating from API v1. 

API version: 2.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// PatchClusterStorage struct for PatchClusterStorage
type PatchClusterStorage struct {
	VolumePropertiesId *string `json:"volumePropertiesId,omitempty"`
	VolumeTypeId *string `json:"volumeTypeId,omitempty"`
	Iops *string `json:"iops,omitempty"`
	Size *string `json:"size,omitempty"`
	// Unused
	Throughput *string `json:"throughput,omitempty"`
}

// NewPatchClusterStorage instantiates a new PatchClusterStorage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchClusterStorage() *PatchClusterStorage {
	this := PatchClusterStorage{}
	return &this
}

// NewPatchClusterStorageWithDefaults instantiates a new PatchClusterStorage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchClusterStorageWithDefaults() *PatchClusterStorage {
	this := PatchClusterStorage{}
	return &this
}

// GetVolumePropertiesId returns the VolumePropertiesId field value if set, zero value otherwise.
func (o *PatchClusterStorage) GetVolumePropertiesId() string {
	if o == nil || o.VolumePropertiesId == nil {
		var ret string
		return ret
	}
	return *o.VolumePropertiesId
}

// GetVolumePropertiesIdOk returns a tuple with the VolumePropertiesId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchClusterStorage) GetVolumePropertiesIdOk() (*string, bool) {
	if o == nil || o.VolumePropertiesId == nil {
		return nil, false
	}
	return o.VolumePropertiesId, true
}

// HasVolumePropertiesId returns a boolean if a field has been set.
func (o *PatchClusterStorage) HasVolumePropertiesId() bool {
	if o != nil && o.VolumePropertiesId != nil {
		return true
	}

	return false
}

// SetVolumePropertiesId gets a reference to the given string and assigns it to the VolumePropertiesId field.
func (o *PatchClusterStorage) SetVolumePropertiesId(v string) {
	o.VolumePropertiesId = &v
}

// GetVolumeTypeId returns the VolumeTypeId field value if set, zero value otherwise.
func (o *PatchClusterStorage) GetVolumeTypeId() string {
	if o == nil || o.VolumeTypeId == nil {
		var ret string
		return ret
	}
	return *o.VolumeTypeId
}

// GetVolumeTypeIdOk returns a tuple with the VolumeTypeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchClusterStorage) GetVolumeTypeIdOk() (*string, bool) {
	if o == nil || o.VolumeTypeId == nil {
		return nil, false
	}
	return o.VolumeTypeId, true
}

// HasVolumeTypeId returns a boolean if a field has been set.
func (o *PatchClusterStorage) HasVolumeTypeId() bool {
	if o != nil && o.VolumeTypeId != nil {
		return true
	}

	return false
}

// SetVolumeTypeId gets a reference to the given string and assigns it to the VolumeTypeId field.
func (o *PatchClusterStorage) SetVolumeTypeId(v string) {
	o.VolumeTypeId = &v
}

// GetIops returns the Iops field value if set, zero value otherwise.
func (o *PatchClusterStorage) GetIops() string {
	if o == nil || o.Iops == nil {
		var ret string
		return ret
	}
	return *o.Iops
}

// GetIopsOk returns a tuple with the Iops field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchClusterStorage) GetIopsOk() (*string, bool) {
	if o == nil || o.Iops == nil {
		return nil, false
	}
	return o.Iops, true
}

// HasIops returns a boolean if a field has been set.
func (o *PatchClusterStorage) HasIops() bool {
	if o != nil && o.Iops != nil {
		return true
	}

	return false
}

// SetIops gets a reference to the given string and assigns it to the Iops field.
func (o *PatchClusterStorage) SetIops(v string) {
	o.Iops = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *PatchClusterStorage) GetSize() string {
	if o == nil || o.Size == nil {
		var ret string
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchClusterStorage) GetSizeOk() (*string, bool) {
	if o == nil || o.Size == nil {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *PatchClusterStorage) HasSize() bool {
	if o != nil && o.Size != nil {
		return true
	}

	return false
}

// SetSize gets a reference to the given string and assigns it to the Size field.
func (o *PatchClusterStorage) SetSize(v string) {
	o.Size = &v
}

// GetThroughput returns the Throughput field value if set, zero value otherwise.
func (o *PatchClusterStorage) GetThroughput() string {
	if o == nil || o.Throughput == nil {
		var ret string
		return ret
	}
	return *o.Throughput
}

// GetThroughputOk returns a tuple with the Throughput field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchClusterStorage) GetThroughputOk() (*string, bool) {
	if o == nil || o.Throughput == nil {
		return nil, false
	}
	return o.Throughput, true
}

// HasThroughput returns a boolean if a field has been set.
func (o *PatchClusterStorage) HasThroughput() bool {
	if o != nil && o.Throughput != nil {
		return true
	}

	return false
}

// SetThroughput gets a reference to the given string and assigns it to the Throughput field.
func (o *PatchClusterStorage) SetThroughput(v string) {
	o.Throughput = &v
}

func (o PatchClusterStorage) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.VolumePropertiesId != nil {
		toSerialize["volumePropertiesId"] = o.VolumePropertiesId
	}
	if o.VolumeTypeId != nil {
		toSerialize["volumeTypeId"] = o.VolumeTypeId
	}
	if o.Iops != nil {
		toSerialize["iops"] = o.Iops
	}
	if o.Size != nil {
		toSerialize["size"] = o.Size
	}
	if o.Throughput != nil {
		toSerialize["throughput"] = o.Throughput
	}
	return json.Marshal(toSerialize)
}

type NullablePatchClusterStorage struct {
	value *PatchClusterStorage
	isSet bool
}

func (v NullablePatchClusterStorage) Get() *PatchClusterStorage {
	return v.value
}

func (v *NullablePatchClusterStorage) Set(val *PatchClusterStorage) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchClusterStorage) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchClusterStorage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchClusterStorage(val *PatchClusterStorage) *NullablePatchClusterStorage {
	return &NullablePatchClusterStorage{value: val, isSet: true}
}

func (v NullablePatchClusterStorage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchClusterStorage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


