/*
BigAnimal

BigAnimal REST API v2 <br /><br /> Please visit [API v2 Changelog page](/api/docs/v2migration.html) for information about migrating from API v1. 

API version: 2.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetBeneficiaryValidation200ResponseData struct for GetBeneficiaryValidation200ResponseData
type GetBeneficiaryValidation200ResponseData struct {
	Result string `json:"result"`
}

// NewGetBeneficiaryValidation200ResponseData instantiates a new GetBeneficiaryValidation200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetBeneficiaryValidation200ResponseData(result string) *GetBeneficiaryValidation200ResponseData {
	this := GetBeneficiaryValidation200ResponseData{}
	this.Result = result
	return &this
}

// NewGetBeneficiaryValidation200ResponseDataWithDefaults instantiates a new GetBeneficiaryValidation200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetBeneficiaryValidation200ResponseDataWithDefaults() *GetBeneficiaryValidation200ResponseData {
	this := GetBeneficiaryValidation200ResponseData{}
	return &this
}

// GetResult returns the Result field value
func (o *GetBeneficiaryValidation200ResponseData) GetResult() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *GetBeneficiaryValidation200ResponseData) GetResultOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Result, true
}

// SetResult sets field value
func (o *GetBeneficiaryValidation200ResponseData) SetResult(v string) {
	o.Result = v
}

func (o GetBeneficiaryValidation200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["result"] = o.Result
	}
	return json.Marshal(toSerialize)
}

type NullableGetBeneficiaryValidation200ResponseData struct {
	value *GetBeneficiaryValidation200ResponseData
	isSet bool
}

func (v NullableGetBeneficiaryValidation200ResponseData) Get() *GetBeneficiaryValidation200ResponseData {
	return v.value
}

func (v *NullableGetBeneficiaryValidation200ResponseData) Set(val *GetBeneficiaryValidation200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableGetBeneficiaryValidation200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableGetBeneficiaryValidation200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetBeneficiaryValidation200ResponseData(val *GetBeneficiaryValidation200ResponseData) *NullableGetBeneficiaryValidation200ResponseData {
	return &NullableGetBeneficiaryValidation200ResponseData{value: val, isSet: true}
}

func (v NullableGetBeneficiaryValidation200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetBeneficiaryValidation200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


