/*
BigAnimal

BigAnimal REST API v2 <br /><br /> Please visit [API v2 Changelog page](/api/docs/v2migration.html) for information about migrating from API v1. 

API version: 2.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetRegisteredCloudProvider200Response struct for GetRegisteredCloudProvider200Response
type GetRegisteredCloudProvider200Response struct {
	ExternalId *string `json:"externalId,omitempty"`
	RoleArn *string `json:"roleArn,omitempty"`
	PolicyArn *string `json:"policyArn,omitempty"`
}

// NewGetRegisteredCloudProvider200Response instantiates a new GetRegisteredCloudProvider200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRegisteredCloudProvider200Response() *GetRegisteredCloudProvider200Response {
	this := GetRegisteredCloudProvider200Response{}
	return &this
}

// NewGetRegisteredCloudProvider200ResponseWithDefaults instantiates a new GetRegisteredCloudProvider200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRegisteredCloudProvider200ResponseWithDefaults() *GetRegisteredCloudProvider200Response {
	this := GetRegisteredCloudProvider200Response{}
	return &this
}

// GetExternalId returns the ExternalId field value if set, zero value otherwise.
func (o *GetRegisteredCloudProvider200Response) GetExternalId() string {
	if o == nil || o.ExternalId == nil {
		var ret string
		return ret
	}
	return *o.ExternalId
}

// GetExternalIdOk returns a tuple with the ExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRegisteredCloudProvider200Response) GetExternalIdOk() (*string, bool) {
	if o == nil || o.ExternalId == nil {
		return nil, false
	}
	return o.ExternalId, true
}

// HasExternalId returns a boolean if a field has been set.
func (o *GetRegisteredCloudProvider200Response) HasExternalId() bool {
	if o != nil && o.ExternalId != nil {
		return true
	}

	return false
}

// SetExternalId gets a reference to the given string and assigns it to the ExternalId field.
func (o *GetRegisteredCloudProvider200Response) SetExternalId(v string) {
	o.ExternalId = &v
}

// GetRoleArn returns the RoleArn field value if set, zero value otherwise.
func (o *GetRegisteredCloudProvider200Response) GetRoleArn() string {
	if o == nil || o.RoleArn == nil {
		var ret string
		return ret
	}
	return *o.RoleArn
}

// GetRoleArnOk returns a tuple with the RoleArn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRegisteredCloudProvider200Response) GetRoleArnOk() (*string, bool) {
	if o == nil || o.RoleArn == nil {
		return nil, false
	}
	return o.RoleArn, true
}

// HasRoleArn returns a boolean if a field has been set.
func (o *GetRegisteredCloudProvider200Response) HasRoleArn() bool {
	if o != nil && o.RoleArn != nil {
		return true
	}

	return false
}

// SetRoleArn gets a reference to the given string and assigns it to the RoleArn field.
func (o *GetRegisteredCloudProvider200Response) SetRoleArn(v string) {
	o.RoleArn = &v
}

// GetPolicyArn returns the PolicyArn field value if set, zero value otherwise.
func (o *GetRegisteredCloudProvider200Response) GetPolicyArn() string {
	if o == nil || o.PolicyArn == nil {
		var ret string
		return ret
	}
	return *o.PolicyArn
}

// GetPolicyArnOk returns a tuple with the PolicyArn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRegisteredCloudProvider200Response) GetPolicyArnOk() (*string, bool) {
	if o == nil || o.PolicyArn == nil {
		return nil, false
	}
	return o.PolicyArn, true
}

// HasPolicyArn returns a boolean if a field has been set.
func (o *GetRegisteredCloudProvider200Response) HasPolicyArn() bool {
	if o != nil && o.PolicyArn != nil {
		return true
	}

	return false
}

// SetPolicyArn gets a reference to the given string and assigns it to the PolicyArn field.
func (o *GetRegisteredCloudProvider200Response) SetPolicyArn(v string) {
	o.PolicyArn = &v
}

func (o GetRegisteredCloudProvider200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ExternalId != nil {
		toSerialize["externalId"] = o.ExternalId
	}
	if o.RoleArn != nil {
		toSerialize["roleArn"] = o.RoleArn
	}
	if o.PolicyArn != nil {
		toSerialize["policyArn"] = o.PolicyArn
	}
	return json.Marshal(toSerialize)
}

type NullableGetRegisteredCloudProvider200Response struct {
	value *GetRegisteredCloudProvider200Response
	isSet bool
}

func (v NullableGetRegisteredCloudProvider200Response) Get() *GetRegisteredCloudProvider200Response {
	return v.value
}

func (v *NullableGetRegisteredCloudProvider200Response) Set(val *GetRegisteredCloudProvider200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRegisteredCloudProvider200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRegisteredCloudProvider200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRegisteredCloudProvider200Response(val *GetRegisteredCloudProvider200Response) *NullableGetRegisteredCloudProvider200Response {
	return &NullableGetRegisteredCloudProvider200Response{value: val, isSet: true}
}

func (v NullableGetRegisteredCloudProvider200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRegisteredCloudProvider200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


