/*
BigAnimal

BigAnimal REST API v2 <br /><br /> Please visit [API v2 Changelog page](/api/docs/v2migration.html) for information about migrating from API v1. 

API version: 2.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CreateClusterProvider struct for CreateClusterProvider
type CreateClusterProvider struct {
	CloudProviderId string `json:"cloudProviderId"`
}

// NewCreateClusterProvider instantiates a new CreateClusterProvider object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateClusterProvider(cloudProviderId string) *CreateClusterProvider {
	this := CreateClusterProvider{}
	this.CloudProviderId = cloudProviderId
	return &this
}

// NewCreateClusterProviderWithDefaults instantiates a new CreateClusterProvider object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateClusterProviderWithDefaults() *CreateClusterProvider {
	this := CreateClusterProvider{}
	return &this
}

// GetCloudProviderId returns the CloudProviderId field value
func (o *CreateClusterProvider) GetCloudProviderId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CloudProviderId
}

// GetCloudProviderIdOk returns a tuple with the CloudProviderId field value
// and a boolean to check if the value has been set.
func (o *CreateClusterProvider) GetCloudProviderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CloudProviderId, true
}

// SetCloudProviderId sets field value
func (o *CreateClusterProvider) SetCloudProviderId(v string) {
	o.CloudProviderId = v
}

func (o CreateClusterProvider) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["cloudProviderId"] = o.CloudProviderId
	}
	return json.Marshal(toSerialize)
}

type NullableCreateClusterProvider struct {
	value *CreateClusterProvider
	isSet bool
}

func (v NullableCreateClusterProvider) Get() *CreateClusterProvider {
	return v.value
}

func (v *NullableCreateClusterProvider) Set(val *CreateClusterProvider) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateClusterProvider) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateClusterProvider) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateClusterProvider(val *CreateClusterProvider) *NullableCreateClusterProvider {
	return &NullableCreateClusterProvider{value: val, isSet: true}
}

func (v NullableCreateClusterProvider) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateClusterProvider) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


