/*
BigAnimal

BigAnimal REST API v2 <br /><br /> Please visit [API v2 Changelog page](/api/docs/v2migration.html) for information about migrating from API v1.

API version: 2.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// Model403 struct for Model403
type Model403 struct {
	Error *Error401 `json:"error,omitempty"`
}

// NewModel403 instantiates a new Model403 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModel403() *Model403 {
	this := Model403{}
	return &this
}

// NewModel403WithDefaults instantiates a new Model403 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModel403WithDefaults() *Model403 {
	this := Model403{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *Model403) GetError() Error401 {
	if o == nil || o.Error == nil {
		var ret Error401
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Model403) GetErrorOk() (*Error401, bool) {
	if o == nil || o.Error == nil {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *Model403) HasError() bool {
	if o != nil && o.Error != nil {
		return true
	}

	return false
}

// SetError gets a reference to the given Error401 and assigns it to the Error field.
func (o *Model403) SetError(v Error401) {
	o.Error = &v
}

func (o Model403) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Error != nil {
		toSerialize["error"] = o.Error
	}
	return json.Marshal(toSerialize)
}

type NullableModel403 struct {
	value *Model403
	isSet bool
}

func (v NullableModel403) Get() *Model403 {
	return v.value
}

func (v *NullableModel403) Set(val *Model403) {
	v.value = val
	v.isSet = true
}

func (v NullableModel403) IsSet() bool {
	return v.isSet
}

func (v *NullableModel403) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModel403(val *Model403) *NullableModel403 {
	return &NullableModel403{value: val, isSet: true}
}

func (v NullableModel403) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModel403) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


