/*
BigAnimal

BigAnimal REST API v2 <br /><br /> Please visit [API v2 Changelog page](/api/docs/v2migration.html) for information about migrating from API v1. 

API version: 2.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetCloudProviderRegions200Response struct for GetCloudProviderRegions200Response
type GetCloudProviderRegions200Response struct {
	Data []CloudProviderRegion `json:"data"`
}

// NewGetCloudProviderRegions200Response instantiates a new GetCloudProviderRegions200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetCloudProviderRegions200Response(data []CloudProviderRegion) *GetCloudProviderRegions200Response {
	this := GetCloudProviderRegions200Response{}
	this.Data = data
	return &this
}

// NewGetCloudProviderRegions200ResponseWithDefaults instantiates a new GetCloudProviderRegions200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetCloudProviderRegions200ResponseWithDefaults() *GetCloudProviderRegions200Response {
	this := GetCloudProviderRegions200Response{}
	return &this
}

// GetData returns the Data field value
func (o *GetCloudProviderRegions200Response) GetData() []CloudProviderRegion {
	if o == nil {
		var ret []CloudProviderRegion
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetCloudProviderRegions200Response) GetDataOk() ([]CloudProviderRegion, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *GetCloudProviderRegions200Response) SetData(v []CloudProviderRegion) {
	o.Data = v
}

func (o GetCloudProviderRegions200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableGetCloudProviderRegions200Response struct {
	value *GetCloudProviderRegions200Response
	isSet bool
}

func (v NullableGetCloudProviderRegions200Response) Get() *GetCloudProviderRegions200Response {
	return v.value
}

func (v *NullableGetCloudProviderRegions200Response) Set(val *GetCloudProviderRegions200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCloudProviderRegions200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCloudProviderRegions200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCloudProviderRegions200Response(val *GetCloudProviderRegions200Response) *NullableGetCloudProviderRegions200Response {
	return &NullableGetCloudProviderRegions200Response{value: val, isSet: true}
}

func (v NullableGetCloudProviderRegions200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCloudProviderRegions200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


