/*
BigAnimal

BigAnimal REST API v2 <br /><br /> Please visit [API v2 Changelog page](/api/docs/v2migration.html) for information about migrating from API v1. 

API version: 2.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ActivateRegion202ResponseData struct for ActivateRegion202ResponseData
type ActivateRegion202ResponseData struct {
	RegionId string `json:"regionId"`
}

// NewActivateRegion202ResponseData instantiates a new ActivateRegion202ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewActivateRegion202ResponseData(regionId string) *ActivateRegion202ResponseData {
	this := ActivateRegion202ResponseData{}
	this.RegionId = regionId
	return &this
}

// NewActivateRegion202ResponseDataWithDefaults instantiates a new ActivateRegion202ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewActivateRegion202ResponseDataWithDefaults() *ActivateRegion202ResponseData {
	this := ActivateRegion202ResponseData{}
	return &this
}

// GetRegionId returns the RegionId field value
func (o *ActivateRegion202ResponseData) GetRegionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RegionId
}

// GetRegionIdOk returns a tuple with the RegionId field value
// and a boolean to check if the value has been set.
func (o *ActivateRegion202ResponseData) GetRegionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RegionId, true
}

// SetRegionId sets field value
func (o *ActivateRegion202ResponseData) SetRegionId(v string) {
	o.RegionId = v
}

func (o ActivateRegion202ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["regionId"] = o.RegionId
	}
	return json.Marshal(toSerialize)
}

type NullableActivateRegion202ResponseData struct {
	value *ActivateRegion202ResponseData
	isSet bool
}

func (v NullableActivateRegion202ResponseData) Get() *ActivateRegion202ResponseData {
	return v.value
}

func (v *NullableActivateRegion202ResponseData) Set(val *ActivateRegion202ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableActivateRegion202ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableActivateRegion202ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableActivateRegion202ResponseData(val *ActivateRegion202ResponseData) *NullableActivateRegion202ResponseData {
	return &NullableActivateRegion202ResponseData{value: val, isSet: true}
}

func (v NullableActivateRegion202ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableActivateRegion202ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


