/*
BigAnimal

BigAnimal REST API v2 <br /><br /> Please visit [API v2 Changelog page](/api/docs/v2migration.html) for information about migrating from API v1. 

API version: 2.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CreateSubscription201Response struct for CreateSubscription201Response
type CreateSubscription201Response struct {
	Data CreateSubscription201ResponseData `json:"data"`
	AdditionalProperties map[string]interface{}
}

type _CreateSubscription201Response CreateSubscription201Response

// NewCreateSubscription201Response instantiates a new CreateSubscription201Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateSubscription201Response(data CreateSubscription201ResponseData) *CreateSubscription201Response {
	this := CreateSubscription201Response{}
	this.Data = data
	return &this
}

// NewCreateSubscription201ResponseWithDefaults instantiates a new CreateSubscription201Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateSubscription201ResponseWithDefaults() *CreateSubscription201Response {
	this := CreateSubscription201Response{}
	return &this
}

// GetData returns the Data field value
func (o *CreateSubscription201Response) GetData() CreateSubscription201ResponseData {
	if o == nil {
		var ret CreateSubscription201ResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CreateSubscription201Response) GetDataOk() (*CreateSubscription201ResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *CreateSubscription201Response) SetData(v CreateSubscription201ResponseData) {
	o.Data = v
}

func (o CreateSubscription201Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *CreateSubscription201Response) UnmarshalJSON(bytes []byte) (err error) {
	varCreateSubscription201Response := _CreateSubscription201Response{}

	if err = json.Unmarshal(bytes, &varCreateSubscription201Response); err == nil {
		*o = CreateSubscription201Response(varCreateSubscription201Response)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateSubscription201Response struct {
	value *CreateSubscription201Response
	isSet bool
}

func (v NullableCreateSubscription201Response) Get() *CreateSubscription201Response {
	return v.value
}

func (v *NullableCreateSubscription201Response) Set(val *CreateSubscription201Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateSubscription201Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateSubscription201Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateSubscription201Response(val *CreateSubscription201Response) *NullableCreateSubscription201Response {
	return &NullableCreateSubscription201Response{value: val, isSet: true}
}

func (v NullableCreateSubscription201Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateSubscription201Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


