/*
BigAnimal

BigAnimal REST API v2 <br /><br /> Please visit [API v2 Changelog page](/api/docs/v2migration.html) for information about migrating from API v1. 

API version: 2.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// UpdatePgConfigTemplate200Response struct for UpdatePgConfigTemplate200Response
type UpdatePgConfigTemplate200Response struct {
	Data UpdatePgConfigTemplate200ResponseData `json:"data"`
}

// NewUpdatePgConfigTemplate200Response instantiates a new UpdatePgConfigTemplate200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdatePgConfigTemplate200Response(data UpdatePgConfigTemplate200ResponseData) *UpdatePgConfigTemplate200Response {
	this := UpdatePgConfigTemplate200Response{}
	this.Data = data
	return &this
}

// NewUpdatePgConfigTemplate200ResponseWithDefaults instantiates a new UpdatePgConfigTemplate200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdatePgConfigTemplate200ResponseWithDefaults() *UpdatePgConfigTemplate200Response {
	this := UpdatePgConfigTemplate200Response{}
	return &this
}

// GetData returns the Data field value
func (o *UpdatePgConfigTemplate200Response) GetData() UpdatePgConfigTemplate200ResponseData {
	if o == nil {
		var ret UpdatePgConfigTemplate200ResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UpdatePgConfigTemplate200Response) GetDataOk() (*UpdatePgConfigTemplate200ResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UpdatePgConfigTemplate200Response) SetData(v UpdatePgConfigTemplate200ResponseData) {
	o.Data = v
}

func (o UpdatePgConfigTemplate200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableUpdatePgConfigTemplate200Response struct {
	value *UpdatePgConfigTemplate200Response
	isSet bool
}

func (v NullableUpdatePgConfigTemplate200Response) Get() *UpdatePgConfigTemplate200Response {
	return v.value
}

func (v *NullableUpdatePgConfigTemplate200Response) Set(val *UpdatePgConfigTemplate200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdatePgConfigTemplate200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdatePgConfigTemplate200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdatePgConfigTemplate200Response(val *UpdatePgConfigTemplate200Response) *NullableUpdatePgConfigTemplate200Response {
	return &NullableUpdatePgConfigTemplate200Response{value: val, isSet: true}
}

func (v NullableUpdatePgConfigTemplate200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdatePgConfigTemplate200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


