/*
BigAnimal

BigAnimal REST API v2 <br /><br /> Please visit [API v2 Changelog page](/api/docs/v2migration.html) for information about migrating from API v1. 

API version: 2.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetPgConfigParameters200Response struct for GetPgConfigParameters200Response
type GetPgConfigParameters200Response struct {
	Data []PgConfigParameter `json:"data"`
}

// NewGetPgConfigParameters200Response instantiates a new GetPgConfigParameters200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetPgConfigParameters200Response(data []PgConfigParameter) *GetPgConfigParameters200Response {
	this := GetPgConfigParameters200Response{}
	this.Data = data
	return &this
}

// NewGetPgConfigParameters200ResponseWithDefaults instantiates a new GetPgConfigParameters200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetPgConfigParameters200ResponseWithDefaults() *GetPgConfigParameters200Response {
	this := GetPgConfigParameters200Response{}
	return &this
}

// GetData returns the Data field value
func (o *GetPgConfigParameters200Response) GetData() []PgConfigParameter {
	if o == nil {
		var ret []PgConfigParameter
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetPgConfigParameters200Response) GetDataOk() ([]PgConfigParameter, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *GetPgConfigParameters200Response) SetData(v []PgConfigParameter) {
	o.Data = v
}

func (o GetPgConfigParameters200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableGetPgConfigParameters200Response struct {
	value *GetPgConfigParameters200Response
	isSet bool
}

func (v NullableGetPgConfigParameters200Response) Get() *GetPgConfigParameters200Response {
	return v.value
}

func (v *NullableGetPgConfigParameters200Response) Set(val *GetPgConfigParameters200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetPgConfigParameters200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetPgConfigParameters200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetPgConfigParameters200Response(val *GetPgConfigParameters200Response) *NullableGetPgConfigParameters200Response {
	return &NullableGetPgConfigParameters200Response{value: val, isSet: true}
}

func (v NullableGetPgConfigParameters200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetPgConfigParameters200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


