/*
BigAnimal

BigAnimal REST API v2 <br /><br /> Please visit [API v2 Changelog page](/api/docs/v2migration.html) for information about migrating from API v1. 

API version: 2.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CreateClusterPgType struct for CreateClusterPgType
type CreateClusterPgType struct {
	PgTypeId string `json:"pgTypeId"`
}

// NewCreateClusterPgType instantiates a new CreateClusterPgType object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateClusterPgType(pgTypeId string) *CreateClusterPgType {
	this := CreateClusterPgType{}
	this.PgTypeId = pgTypeId
	return &this
}

// NewCreateClusterPgTypeWithDefaults instantiates a new CreateClusterPgType object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateClusterPgTypeWithDefaults() *CreateClusterPgType {
	this := CreateClusterPgType{}
	return &this
}

// GetPgTypeId returns the PgTypeId field value
func (o *CreateClusterPgType) GetPgTypeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PgTypeId
}

// GetPgTypeIdOk returns a tuple with the PgTypeId field value
// and a boolean to check if the value has been set.
func (o *CreateClusterPgType) GetPgTypeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PgTypeId, true
}

// SetPgTypeId sets field value
func (o *CreateClusterPgType) SetPgTypeId(v string) {
	o.PgTypeId = v
}

func (o CreateClusterPgType) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["pgTypeId"] = o.PgTypeId
	}
	return json.Marshal(toSerialize)
}

type NullableCreateClusterPgType struct {
	value *CreateClusterPgType
	isSet bool
}

func (v NullableCreateClusterPgType) Get() *CreateClusterPgType {
	return v.value
}

func (v *NullableCreateClusterPgType) Set(val *CreateClusterPgType) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateClusterPgType) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateClusterPgType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateClusterPgType(val *CreateClusterPgType) *NullableCreateClusterPgType {
	return &NullableCreateClusterPgType{value: val, isSet: true}
}

func (v NullableCreateClusterPgType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateClusterPgType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


