/*
BigAnimal

BigAnimal REST API v2 <br /><br /> Please visit [API v2 Changelog page](/api/docs/v2migration.html) for information about migrating from API v1. 

API version: 2.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetCluster200Response struct for GetCluster200Response
type GetCluster200Response struct {
	Data ClusterDetail `json:"data"`
}

// NewGetCluster200Response instantiates a new GetCluster200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetCluster200Response(data ClusterDetail) *GetCluster200Response {
	this := GetCluster200Response{}
	this.Data = data
	return &this
}

// NewGetCluster200ResponseWithDefaults instantiates a new GetCluster200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetCluster200ResponseWithDefaults() *GetCluster200Response {
	this := GetCluster200Response{}
	return &this
}

// GetData returns the Data field value
func (o *GetCluster200Response) GetData() ClusterDetail {
	if o == nil {
		var ret ClusterDetail
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetCluster200Response) GetDataOk() (*ClusterDetail, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GetCluster200Response) SetData(v ClusterDetail) {
	o.Data = v
}

func (o GetCluster200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableGetCluster200Response struct {
	value *GetCluster200Response
	isSet bool
}

func (v NullableGetCluster200Response) Get() *GetCluster200Response {
	return v.value
}

func (v *NullableGetCluster200Response) Set(val *GetCluster200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCluster200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCluster200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCluster200Response(val *GetCluster200Response) *NullableGetCluster200Response {
	return &NullableGetCluster200Response{value: val, isSet: true}
}

func (v NullableGetCluster200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCluster200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


