/*
BigAnimal

BigAnimal REST API v2 <br /><br /> Please visit [API v2 Changelog page](/api/docs/v2migration.html) for information about migrating from API v1. 

API version: 2.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// RunCheckForPasswordStrength200Response struct for RunCheckForPasswordStrength200Response
type RunCheckForPasswordStrength200Response struct {
	Data RunCheckForPasswordStrength200ResponseData `json:"data"`
}

// NewRunCheckForPasswordStrength200Response instantiates a new RunCheckForPasswordStrength200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRunCheckForPasswordStrength200Response(data RunCheckForPasswordStrength200ResponseData) *RunCheckForPasswordStrength200Response {
	this := RunCheckForPasswordStrength200Response{}
	this.Data = data
	return &this
}

// NewRunCheckForPasswordStrength200ResponseWithDefaults instantiates a new RunCheckForPasswordStrength200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRunCheckForPasswordStrength200ResponseWithDefaults() *RunCheckForPasswordStrength200Response {
	this := RunCheckForPasswordStrength200Response{}
	return &this
}

// GetData returns the Data field value
func (o *RunCheckForPasswordStrength200Response) GetData() RunCheckForPasswordStrength200ResponseData {
	if o == nil {
		var ret RunCheckForPasswordStrength200ResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *RunCheckForPasswordStrength200Response) GetDataOk() (*RunCheckForPasswordStrength200ResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *RunCheckForPasswordStrength200Response) SetData(v RunCheckForPasswordStrength200ResponseData) {
	o.Data = v
}

func (o RunCheckForPasswordStrength200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableRunCheckForPasswordStrength200Response struct {
	value *RunCheckForPasswordStrength200Response
	isSet bool
}

func (v NullableRunCheckForPasswordStrength200Response) Get() *RunCheckForPasswordStrength200Response {
	return v.value
}

func (v *NullableRunCheckForPasswordStrength200Response) Set(val *RunCheckForPasswordStrength200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableRunCheckForPasswordStrength200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableRunCheckForPasswordStrength200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRunCheckForPasswordStrength200Response(val *RunCheckForPasswordStrength200Response) *NullableRunCheckForPasswordStrength200Response {
	return &NullableRunCheckForPasswordStrength200Response{value: val, isSet: true}
}

func (v NullableRunCheckForPasswordStrength200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRunCheckForPasswordStrength200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


