/*
BigAnimal

BigAnimal REST API v2 <br /><br /> Please visit [API v2 Changelog page](/api/docs/v2migration.html) for information about migrating from API v1. 

API version: 2.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetCloudProviders200Response struct for GetCloudProviders200Response
type GetCloudProviders200Response struct {
	Data []CloudProvider `json:"data"`
}

// NewGetCloudProviders200Response instantiates a new GetCloudProviders200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetCloudProviders200Response(data []CloudProvider) *GetCloudProviders200Response {
	this := GetCloudProviders200Response{}
	this.Data = data
	return &this
}

// NewGetCloudProviders200ResponseWithDefaults instantiates a new GetCloudProviders200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetCloudProviders200ResponseWithDefaults() *GetCloudProviders200Response {
	this := GetCloudProviders200Response{}
	return &this
}

// GetData returns the Data field value
func (o *GetCloudProviders200Response) GetData() []CloudProvider {
	if o == nil {
		var ret []CloudProvider
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetCloudProviders200Response) GetDataOk() ([]CloudProvider, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *GetCloudProviders200Response) SetData(v []CloudProvider) {
	o.Data = v
}

func (o GetCloudProviders200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableGetCloudProviders200Response struct {
	value *GetCloudProviders200Response
	isSet bool
}

func (v NullableGetCloudProviders200Response) Get() *GetCloudProviders200Response {
	return v.value
}

func (v *NullableGetCloudProviders200Response) Set(val *GetCloudProviders200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCloudProviders200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCloudProviders200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCloudProviders200Response(val *GetCloudProviders200Response) *NullableGetCloudProviders200Response {
	return &NullableGetCloudProviders200Response{value: val, isSet: true}
}

func (v NullableGetCloudProviders200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCloudProviders200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


