/*
BigAnimal

BigAnimal REST API v2 <br /><br /> Please visit [API v2 Changelog page](/api/docs/v2migration.html) for information about migrating from API v1. 

API version: 2.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetConnectionList200ResponseBrokerConfigInfoOidc struct for GetConnectionList200ResponseBrokerConfigInfoOidc
type GetConnectionList200ResponseBrokerConfigInfoOidc struct {
	CallbackUrl *string `json:"callbackUrl,omitempty"`
}

// NewGetConnectionList200ResponseBrokerConfigInfoOidc instantiates a new GetConnectionList200ResponseBrokerConfigInfoOidc object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetConnectionList200ResponseBrokerConfigInfoOidc() *GetConnectionList200ResponseBrokerConfigInfoOidc {
	this := GetConnectionList200ResponseBrokerConfigInfoOidc{}
	return &this
}

// NewGetConnectionList200ResponseBrokerConfigInfoOidcWithDefaults instantiates a new GetConnectionList200ResponseBrokerConfigInfoOidc object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetConnectionList200ResponseBrokerConfigInfoOidcWithDefaults() *GetConnectionList200ResponseBrokerConfigInfoOidc {
	this := GetConnectionList200ResponseBrokerConfigInfoOidc{}
	return &this
}

// GetCallbackUrl returns the CallbackUrl field value if set, zero value otherwise.
func (o *GetConnectionList200ResponseBrokerConfigInfoOidc) GetCallbackUrl() string {
	if o == nil || o.CallbackUrl == nil {
		var ret string
		return ret
	}
	return *o.CallbackUrl
}

// GetCallbackUrlOk returns a tuple with the CallbackUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetConnectionList200ResponseBrokerConfigInfoOidc) GetCallbackUrlOk() (*string, bool) {
	if o == nil || o.CallbackUrl == nil {
		return nil, false
	}
	return o.CallbackUrl, true
}

// HasCallbackUrl returns a boolean if a field has been set.
func (o *GetConnectionList200ResponseBrokerConfigInfoOidc) HasCallbackUrl() bool {
	if o != nil && o.CallbackUrl != nil {
		return true
	}

	return false
}

// SetCallbackUrl gets a reference to the given string and assigns it to the CallbackUrl field.
func (o *GetConnectionList200ResponseBrokerConfigInfoOidc) SetCallbackUrl(v string) {
	o.CallbackUrl = &v
}

func (o GetConnectionList200ResponseBrokerConfigInfoOidc) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.CallbackUrl != nil {
		toSerialize["callbackUrl"] = o.CallbackUrl
	}
	return json.Marshal(toSerialize)
}

type NullableGetConnectionList200ResponseBrokerConfigInfoOidc struct {
	value *GetConnectionList200ResponseBrokerConfigInfoOidc
	isSet bool
}

func (v NullableGetConnectionList200ResponseBrokerConfigInfoOidc) Get() *GetConnectionList200ResponseBrokerConfigInfoOidc {
	return v.value
}

func (v *NullableGetConnectionList200ResponseBrokerConfigInfoOidc) Set(val *GetConnectionList200ResponseBrokerConfigInfoOidc) {
	v.value = val
	v.isSet = true
}

func (v NullableGetConnectionList200ResponseBrokerConfigInfoOidc) IsSet() bool {
	return v.isSet
}

func (v *NullableGetConnectionList200ResponseBrokerConfigInfoOidc) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetConnectionList200ResponseBrokerConfigInfoOidc(val *GetConnectionList200ResponseBrokerConfigInfoOidc) *NullableGetConnectionList200ResponseBrokerConfigInfoOidc {
	return &NullableGetConnectionList200ResponseBrokerConfigInfoOidc{value: val, isSet: true}
}

func (v NullableGetConnectionList200ResponseBrokerConfigInfoOidc) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetConnectionList200ResponseBrokerConfigInfoOidc) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


