/*
BigAnimal

BigAnimal REST API v2 <br /><br /> Please visit [API v2 Changelog page](/api/docs/v2migration.html) for information about migrating from API v1. 

API version: 2.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetConnectionList200ResponseBrokerConfigInfo struct for GetConnectionList200ResponseBrokerConfigInfo
type GetConnectionList200ResponseBrokerConfigInfo struct {
	Saml *GetConnectionList200ResponseBrokerConfigInfoSaml `json:"saml,omitempty"`
	Oidc *GetConnectionList200ResponseBrokerConfigInfoOidc `json:"oidc,omitempty"`
}

// NewGetConnectionList200ResponseBrokerConfigInfo instantiates a new GetConnectionList200ResponseBrokerConfigInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetConnectionList200ResponseBrokerConfigInfo() *GetConnectionList200ResponseBrokerConfigInfo {
	this := GetConnectionList200ResponseBrokerConfigInfo{}
	return &this
}

// NewGetConnectionList200ResponseBrokerConfigInfoWithDefaults instantiates a new GetConnectionList200ResponseBrokerConfigInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetConnectionList200ResponseBrokerConfigInfoWithDefaults() *GetConnectionList200ResponseBrokerConfigInfo {
	this := GetConnectionList200ResponseBrokerConfigInfo{}
	return &this
}

// GetSaml returns the Saml field value if set, zero value otherwise.
func (o *GetConnectionList200ResponseBrokerConfigInfo) GetSaml() GetConnectionList200ResponseBrokerConfigInfoSaml {
	if o == nil || o.Saml == nil {
		var ret GetConnectionList200ResponseBrokerConfigInfoSaml
		return ret
	}
	return *o.Saml
}

// GetSamlOk returns a tuple with the Saml field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetConnectionList200ResponseBrokerConfigInfo) GetSamlOk() (*GetConnectionList200ResponseBrokerConfigInfoSaml, bool) {
	if o == nil || o.Saml == nil {
		return nil, false
	}
	return o.Saml, true
}

// HasSaml returns a boolean if a field has been set.
func (o *GetConnectionList200ResponseBrokerConfigInfo) HasSaml() bool {
	if o != nil && o.Saml != nil {
		return true
	}

	return false
}

// SetSaml gets a reference to the given GetConnectionList200ResponseBrokerConfigInfoSaml and assigns it to the Saml field.
func (o *GetConnectionList200ResponseBrokerConfigInfo) SetSaml(v GetConnectionList200ResponseBrokerConfigInfoSaml) {
	o.Saml = &v
}

// GetOidc returns the Oidc field value if set, zero value otherwise.
func (o *GetConnectionList200ResponseBrokerConfigInfo) GetOidc() GetConnectionList200ResponseBrokerConfigInfoOidc {
	if o == nil || o.Oidc == nil {
		var ret GetConnectionList200ResponseBrokerConfigInfoOidc
		return ret
	}
	return *o.Oidc
}

// GetOidcOk returns a tuple with the Oidc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetConnectionList200ResponseBrokerConfigInfo) GetOidcOk() (*GetConnectionList200ResponseBrokerConfigInfoOidc, bool) {
	if o == nil || o.Oidc == nil {
		return nil, false
	}
	return o.Oidc, true
}

// HasOidc returns a boolean if a field has been set.
func (o *GetConnectionList200ResponseBrokerConfigInfo) HasOidc() bool {
	if o != nil && o.Oidc != nil {
		return true
	}

	return false
}

// SetOidc gets a reference to the given GetConnectionList200ResponseBrokerConfigInfoOidc and assigns it to the Oidc field.
func (o *GetConnectionList200ResponseBrokerConfigInfo) SetOidc(v GetConnectionList200ResponseBrokerConfigInfoOidc) {
	o.Oidc = &v
}

func (o GetConnectionList200ResponseBrokerConfigInfo) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Saml != nil {
		toSerialize["saml"] = o.Saml
	}
	if o.Oidc != nil {
		toSerialize["oidc"] = o.Oidc
	}
	return json.Marshal(toSerialize)
}

type NullableGetConnectionList200ResponseBrokerConfigInfo struct {
	value *GetConnectionList200ResponseBrokerConfigInfo
	isSet bool
}

func (v NullableGetConnectionList200ResponseBrokerConfigInfo) Get() *GetConnectionList200ResponseBrokerConfigInfo {
	return v.value
}

func (v *NullableGetConnectionList200ResponseBrokerConfigInfo) Set(val *GetConnectionList200ResponseBrokerConfigInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableGetConnectionList200ResponseBrokerConfigInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableGetConnectionList200ResponseBrokerConfigInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetConnectionList200ResponseBrokerConfigInfo(val *GetConnectionList200ResponseBrokerConfigInfo) *NullableGetConnectionList200ResponseBrokerConfigInfo {
	return &NullableGetConnectionList200ResponseBrokerConfigInfo{value: val, isSet: true}
}

func (v NullableGetConnectionList200ResponseBrokerConfigInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetConnectionList200ResponseBrokerConfigInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


