/*
BigAnimal

BigAnimal REST API v2 <br /><br /> Please visit [API v2 Changelog page](/api/docs/v2migration.html) for information about migrating from API v1. 

API version: 2.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetUserInfo200Response struct for GetUserInfo200Response
type GetUserInfo200Response struct {
	Data UserInfo `json:"data"`
}

// NewGetUserInfo200Response instantiates a new GetUserInfo200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetUserInfo200Response(data UserInfo) *GetUserInfo200Response {
	this := GetUserInfo200Response{}
	this.Data = data
	return &this
}

// NewGetUserInfo200ResponseWithDefaults instantiates a new GetUserInfo200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetUserInfo200ResponseWithDefaults() *GetUserInfo200Response {
	this := GetUserInfo200Response{}
	return &this
}

// GetData returns the Data field value
func (o *GetUserInfo200Response) GetData() UserInfo {
	if o == nil {
		var ret UserInfo
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetUserInfo200Response) GetDataOk() (*UserInfo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GetUserInfo200Response) SetData(v UserInfo) {
	o.Data = v
}

func (o GetUserInfo200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableGetUserInfo200Response struct {
	value *GetUserInfo200Response
	isSet bool
}

func (v NullableGetUserInfo200Response) Get() *GetUserInfo200Response {
	return v.value
}

func (v *NullableGetUserInfo200Response) Set(val *GetUserInfo200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetUserInfo200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetUserInfo200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetUserInfo200Response(val *GetUserInfo200Response) *NullableGetUserInfo200Response {
	return &NullableGetUserInfo200Response{value: val, isSet: true}
}

func (v NullableGetUserInfo200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetUserInfo200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


