/*
BigAnimal

BigAnimal REST API v2 <br /><br /> Please visit [API v2 Changelog page](/api/docs/v2migration.html) for information about migrating from API v1. 

API version: 2.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CreatePgConfigTemplate struct for CreatePgConfigTemplate
type CreatePgConfigTemplate struct {
	MachineSettings [][]string `json:"machineSettings"`
	PgTypeId string `json:"pgTypeId"`
	PgVersionId string `json:"pgVersionId"`
	TemplateDescription string `json:"templateDescription"`
	TemplateName string `json:"templateName"`
	TemplateSettings [][]string `json:"templateSettings"`
}

// NewCreatePgConfigTemplate instantiates a new CreatePgConfigTemplate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatePgConfigTemplate(machineSettings [][]string, pgTypeId string, pgVersionId string, templateDescription string, templateName string, templateSettings [][]string) *CreatePgConfigTemplate {
	this := CreatePgConfigTemplate{}
	this.MachineSettings = machineSettings
	this.PgTypeId = pgTypeId
	this.PgVersionId = pgVersionId
	this.TemplateDescription = templateDescription
	this.TemplateName = templateName
	this.TemplateSettings = templateSettings
	return &this
}

// NewCreatePgConfigTemplateWithDefaults instantiates a new CreatePgConfigTemplate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatePgConfigTemplateWithDefaults() *CreatePgConfigTemplate {
	this := CreatePgConfigTemplate{}
	return &this
}

// GetMachineSettings returns the MachineSettings field value
func (o *CreatePgConfigTemplate) GetMachineSettings() [][]string {
	if o == nil {
		var ret [][]string
		return ret
	}

	return o.MachineSettings
}

// GetMachineSettingsOk returns a tuple with the MachineSettings field value
// and a boolean to check if the value has been set.
func (o *CreatePgConfigTemplate) GetMachineSettingsOk() ([][]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MachineSettings, true
}

// SetMachineSettings sets field value
func (o *CreatePgConfigTemplate) SetMachineSettings(v [][]string) {
	o.MachineSettings = v
}

// GetPgTypeId returns the PgTypeId field value
func (o *CreatePgConfigTemplate) GetPgTypeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PgTypeId
}

// GetPgTypeIdOk returns a tuple with the PgTypeId field value
// and a boolean to check if the value has been set.
func (o *CreatePgConfigTemplate) GetPgTypeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PgTypeId, true
}

// SetPgTypeId sets field value
func (o *CreatePgConfigTemplate) SetPgTypeId(v string) {
	o.PgTypeId = v
}

// GetPgVersionId returns the PgVersionId field value
func (o *CreatePgConfigTemplate) GetPgVersionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PgVersionId
}

// GetPgVersionIdOk returns a tuple with the PgVersionId field value
// and a boolean to check if the value has been set.
func (o *CreatePgConfigTemplate) GetPgVersionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PgVersionId, true
}

// SetPgVersionId sets field value
func (o *CreatePgConfigTemplate) SetPgVersionId(v string) {
	o.PgVersionId = v
}

// GetTemplateDescription returns the TemplateDescription field value
func (o *CreatePgConfigTemplate) GetTemplateDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TemplateDescription
}

// GetTemplateDescriptionOk returns a tuple with the TemplateDescription field value
// and a boolean to check if the value has been set.
func (o *CreatePgConfigTemplate) GetTemplateDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TemplateDescription, true
}

// SetTemplateDescription sets field value
func (o *CreatePgConfigTemplate) SetTemplateDescription(v string) {
	o.TemplateDescription = v
}

// GetTemplateName returns the TemplateName field value
func (o *CreatePgConfigTemplate) GetTemplateName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TemplateName
}

// GetTemplateNameOk returns a tuple with the TemplateName field value
// and a boolean to check if the value has been set.
func (o *CreatePgConfigTemplate) GetTemplateNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TemplateName, true
}

// SetTemplateName sets field value
func (o *CreatePgConfigTemplate) SetTemplateName(v string) {
	o.TemplateName = v
}

// GetTemplateSettings returns the TemplateSettings field value
func (o *CreatePgConfigTemplate) GetTemplateSettings() [][]string {
	if o == nil {
		var ret [][]string
		return ret
	}

	return o.TemplateSettings
}

// GetTemplateSettingsOk returns a tuple with the TemplateSettings field value
// and a boolean to check if the value has been set.
func (o *CreatePgConfigTemplate) GetTemplateSettingsOk() ([][]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TemplateSettings, true
}

// SetTemplateSettings sets field value
func (o *CreatePgConfigTemplate) SetTemplateSettings(v [][]string) {
	o.TemplateSettings = v
}

func (o CreatePgConfigTemplate) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["machineSettings"] = o.MachineSettings
	}
	if true {
		toSerialize["pgTypeId"] = o.PgTypeId
	}
	if true {
		toSerialize["pgVersionId"] = o.PgVersionId
	}
	if true {
		toSerialize["templateDescription"] = o.TemplateDescription
	}
	if true {
		toSerialize["templateName"] = o.TemplateName
	}
	if true {
		toSerialize["templateSettings"] = o.TemplateSettings
	}
	return json.Marshal(toSerialize)
}

type NullableCreatePgConfigTemplate struct {
	value *CreatePgConfigTemplate
	isSet bool
}

func (v NullableCreatePgConfigTemplate) Get() *CreatePgConfigTemplate {
	return v.value
}

func (v *NullableCreatePgConfigTemplate) Set(val *CreatePgConfigTemplate) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatePgConfigTemplate) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatePgConfigTemplate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatePgConfigTemplate(val *CreatePgConfigTemplate) *NullableCreatePgConfigTemplate {
	return &NullableCreatePgConfigTemplate{value: val, isSet: true}
}

func (v NullableCreatePgConfigTemplate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatePgConfigTemplate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


