/*
BigAnimal

BigAnimal REST API v2 <br /><br /> Please visit [API v2 Changelog page](/api/docs/v2migration.html) for information about migrating from API v1. 

API version: 2.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// 401ErrorErrorsInner struct for 401ErrorErrorsInner
type 401ErrorErrorsInner struct {
	Path *string `json:"path,omitempty"`
	Message *string `json:"message,omitempty"`
	ErrorCode *string `json:"errorCode,omitempty"`
}

// New401ErrorErrorsInner instantiates a new 401ErrorErrorsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func New401ErrorErrorsInner() *401ErrorErrorsInner {
	this := 401ErrorErrorsInner{}
	return &this
}

// New401ErrorErrorsInnerWithDefaults instantiates a new 401ErrorErrorsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func New401ErrorErrorsInnerWithDefaults() *401ErrorErrorsInner {
	this := 401ErrorErrorsInner{}
	return &this
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *401ErrorErrorsInner) GetPath() string {
	if o == nil || o.Path == nil {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *401ErrorErrorsInner) GetPathOk() (*string, bool) {
	if o == nil || o.Path == nil {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *401ErrorErrorsInner) HasPath() bool {
	if o != nil && o.Path != nil {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *401ErrorErrorsInner) SetPath(v string) {
	o.Path = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *401ErrorErrorsInner) GetMessage() string {
	if o == nil || o.Message == nil {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *401ErrorErrorsInner) GetMessageOk() (*string, bool) {
	if o == nil || o.Message == nil {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *401ErrorErrorsInner) HasMessage() bool {
	if o != nil && o.Message != nil {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *401ErrorErrorsInner) SetMessage(v string) {
	o.Message = &v
}

// GetErrorCode returns the ErrorCode field value if set, zero value otherwise.
func (o *401ErrorErrorsInner) GetErrorCode() string {
	if o == nil || o.ErrorCode == nil {
		var ret string
		return ret
	}
	return *o.ErrorCode
}

// GetErrorCodeOk returns a tuple with the ErrorCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *401ErrorErrorsInner) GetErrorCodeOk() (*string, bool) {
	if o == nil || o.ErrorCode == nil {
		return nil, false
	}
	return o.ErrorCode, true
}

// HasErrorCode returns a boolean if a field has been set.
func (o *401ErrorErrorsInner) HasErrorCode() bool {
	if o != nil && o.ErrorCode != nil {
		return true
	}

	return false
}

// SetErrorCode gets a reference to the given string and assigns it to the ErrorCode field.
func (o *401ErrorErrorsInner) SetErrorCode(v string) {
	o.ErrorCode = &v
}

func (o 401ErrorErrorsInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Path != nil {
		toSerialize["path"] = o.Path
	}
	if o.Message != nil {
		toSerialize["message"] = o.Message
	}
	if o.ErrorCode != nil {
		toSerialize["errorCode"] = o.ErrorCode
	}
	return json.Marshal(toSerialize)
}

type Nullable401ErrorErrorsInner struct {
	value *401ErrorErrorsInner
	isSet bool
}

func (v Nullable401ErrorErrorsInner) Get() *401ErrorErrorsInner {
	return v.value
}

func (v *Nullable401ErrorErrorsInner) Set(val *401ErrorErrorsInner) {
	v.value = val
	v.isSet = true
}

func (v Nullable401ErrorErrorsInner) IsSet() bool {
	return v.isSet
}

func (v *Nullable401ErrorErrorsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullable401ErrorErrorsInner(val *401ErrorErrorsInner) *Nullable401ErrorErrorsInner {
	return &Nullable401ErrorErrorsInner{value: val, isSet: true}
}

func (v Nullable401ErrorErrorsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *Nullable401ErrorErrorsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


