/*
BigAnimal

BigAnimal REST API v2 <br /><br /> Please visit [API v2 Changelog page](/api/docs/v2migration.html) for information about migrating from API v1. 

API version: 2.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CreateCluster202Response struct for CreateCluster202Response
type CreateCluster202Response struct {
	Data CreateCluster202ResponseData `json:"data"`
}

// NewCreateCluster202Response instantiates a new CreateCluster202Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCluster202Response(data CreateCluster202ResponseData) *CreateCluster202Response {
	this := CreateCluster202Response{}
	this.Data = data
	return &this
}

// NewCreateCluster202ResponseWithDefaults instantiates a new CreateCluster202Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCluster202ResponseWithDefaults() *CreateCluster202Response {
	this := CreateCluster202Response{}
	return &this
}

// GetData returns the Data field value
func (o *CreateCluster202Response) GetData() CreateCluster202ResponseData {
	if o == nil {
		var ret CreateCluster202ResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CreateCluster202Response) GetDataOk() (*CreateCluster202ResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *CreateCluster202Response) SetData(v CreateCluster202ResponseData) {
	o.Data = v
}

func (o CreateCluster202Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableCreateCluster202Response struct {
	value *CreateCluster202Response
	isSet bool
}

func (v NullableCreateCluster202Response) Get() *CreateCluster202Response {
	return v.value
}

func (v *NullableCreateCluster202Response) Set(val *CreateCluster202Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCluster202Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCluster202Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCluster202Response(val *CreateCluster202Response) *NullableCreateCluster202Response {
	return &NullableCreateCluster202Response{value: val, isSet: true}
}

func (v NullableCreateCluster202Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCluster202Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


