/*
BigAnimal

BigAnimal REST API v2 <br /><br /> Please visit [API v2 Changelog page](/api/docs/v2migration.html) for information about migrating from API v1. 

API version: 2.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// EvaluatePgConfigTemplate struct for EvaluatePgConfigTemplate
type EvaluatePgConfigTemplate struct {
	MachineSettings [][]string `json:"machineSettings"`
	PgConfigTemplateId string `json:"pgConfigTemplateId"`
}

// NewEvaluatePgConfigTemplate instantiates a new EvaluatePgConfigTemplate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEvaluatePgConfigTemplate(machineSettings [][]string, pgConfigTemplateId string) *EvaluatePgConfigTemplate {
	this := EvaluatePgConfigTemplate{}
	this.MachineSettings = machineSettings
	this.PgConfigTemplateId = pgConfigTemplateId
	return &this
}

// NewEvaluatePgConfigTemplateWithDefaults instantiates a new EvaluatePgConfigTemplate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEvaluatePgConfigTemplateWithDefaults() *EvaluatePgConfigTemplate {
	this := EvaluatePgConfigTemplate{}
	return &this
}

// GetMachineSettings returns the MachineSettings field value
func (o *EvaluatePgConfigTemplate) GetMachineSettings() [][]string {
	if o == nil {
		var ret [][]string
		return ret
	}

	return o.MachineSettings
}

// GetMachineSettingsOk returns a tuple with the MachineSettings field value
// and a boolean to check if the value has been set.
func (o *EvaluatePgConfigTemplate) GetMachineSettingsOk() ([][]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MachineSettings, true
}

// SetMachineSettings sets field value
func (o *EvaluatePgConfigTemplate) SetMachineSettings(v [][]string) {
	o.MachineSettings = v
}

// GetPgConfigTemplateId returns the PgConfigTemplateId field value
func (o *EvaluatePgConfigTemplate) GetPgConfigTemplateId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PgConfigTemplateId
}

// GetPgConfigTemplateIdOk returns a tuple with the PgConfigTemplateId field value
// and a boolean to check if the value has been set.
func (o *EvaluatePgConfigTemplate) GetPgConfigTemplateIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PgConfigTemplateId, true
}

// SetPgConfigTemplateId sets field value
func (o *EvaluatePgConfigTemplate) SetPgConfigTemplateId(v string) {
	o.PgConfigTemplateId = v
}

func (o EvaluatePgConfigTemplate) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["machineSettings"] = o.MachineSettings
	}
	if true {
		toSerialize["pgConfigTemplateId"] = o.PgConfigTemplateId
	}
	return json.Marshal(toSerialize)
}

type NullableEvaluatePgConfigTemplate struct {
	value *EvaluatePgConfigTemplate
	isSet bool
}

func (v NullableEvaluatePgConfigTemplate) Get() *EvaluatePgConfigTemplate {
	return v.value
}

func (v *NullableEvaluatePgConfigTemplate) Set(val *EvaluatePgConfigTemplate) {
	v.value = val
	v.isSet = true
}

func (v NullableEvaluatePgConfigTemplate) IsSet() bool {
	return v.isSet
}

func (v *NullableEvaluatePgConfigTemplate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEvaluatePgConfigTemplate(val *EvaluatePgConfigTemplate) *NullableEvaluatePgConfigTemplate {
	return &NullableEvaluatePgConfigTemplate{value: val, isSet: true}
}

func (v NullableEvaluatePgConfigTemplate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEvaluatePgConfigTemplate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


