/*
BigAnimal

BigAnimal REST API v2 <br /><br /> Please visit [API v2 Changelog page](/api/docs/v2migration.html) for information about migrating from API v1. 

API version: 2.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetOutages200Response struct for GetOutages200Response
type GetOutages200Response struct {
	Data []string `json:"data"`
}

// NewGetOutages200Response instantiates a new GetOutages200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetOutages200Response(data []string) *GetOutages200Response {
	this := GetOutages200Response{}
	this.Data = data
	return &this
}

// NewGetOutages200ResponseWithDefaults instantiates a new GetOutages200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetOutages200ResponseWithDefaults() *GetOutages200Response {
	this := GetOutages200Response{}
	return &this
}

// GetData returns the Data field value
func (o *GetOutages200Response) GetData() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetOutages200Response) GetDataOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *GetOutages200Response) SetData(v []string) {
	o.Data = v
}

func (o GetOutages200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableGetOutages200Response struct {
	value *GetOutages200Response
	isSet bool
}

func (v NullableGetOutages200Response) Get() *GetOutages200Response {
	return v.value
}

func (v *NullableGetOutages200Response) Set(val *GetOutages200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetOutages200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetOutages200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetOutages200Response(val *GetOutages200Response) *NullableGetOutages200Response {
	return &NullableGetOutages200Response{value: val, isSet: true}
}

func (v NullableGetOutages200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetOutages200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


