#  Run these commands at repo root to enable pre-commit in local development environment
#  brew install pre-commit
#  pre-commit install
#  pre-commit install --hook-type commit-msg
#  pre-commit install --hook-type pre-push
# Refer https://pre-commit.com for more information
# Refer https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
        stages: [push]
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-json
        types: [file]  # override `types: [json]`
        files: \.(json|json\.tpl)$
      - id: pretty-format-json
        types: [file]  # override `types: [json]`
        files: \.(json|json\.tpl)$
        args: [--autofix]

  # pre-commit hook to verify commit messages are conventional commit compliant
  # NOTE: not using the latest version of commitizen, because it doesn't verify
  #       the commit, if it's committed with `git commit -v`. Probably a bug
  #       in the commitizen side. Needs more investigation
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.20.5
    hooks:
      - id: commitizen
        stages: [commit-msg]

  # pre-commit hooks for golang
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-vet
      - id: golangci-lint
      - id: go-mod-tidy

  # Lint: Dockerfile
  - repo: https://github.com/hadolint/hadolint.git
    rev: v2.12.0
    hooks:
      - id: hadolint-docker

  # Lint: protofile
  - repo: https://github.com/yoheimuta/protolint
    rev: v0.42.0
    hooks:
      - id: protolint

  # Lint: Bash scripts
  - repo: https://github.com/openstack-dev/bashate.git
    rev: 2.1.1
    hooks:
      - id: bashate

  # Lint: Shell scripts
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.8.0.4
    hooks:
      - id: shellcheck
        args: [ "-x" ]
