// Code generated by scripts/api/main.go. DO NOT EDIT.
/*
 * BigAnimal
 *
 * BigAnimal REST API v2 <br /><br /> Please visit [API v2 Changelog page](/api/docs/v2migration.html) for information about migrating from API v1.
 *
 * API version: 17.28.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package apiv2

import "encoding/json"

type ClustersClusterIdBody1 struct {
	AllowedIpRanges       *[]AllowedIpRange                    `json:"allowedIpRanges,omitempty"`
	BackupRetentionPeriod *string                              `json:"backupRetentionPeriod,omitempty"`
	ClusterArchitecture   *ClustersClusterArchitecture         `json:"clusterArchitecture,omitempty"`
	ClusterName           *string                              `json:"clusterName,omitempty"`
	InstanceType          *ClustersInstanceType                `json:"instanceType,omitempty"`
	Password              *string                              `json:"password,omitempty"`
	PgConfig              *[]ClustersClusterArchitectureParams `json:"pgConfig,omitempty"`
	PrivateNetworking     *bool                                `json:"privateNetworking,omitempty"`
	Replicas              *float64                             `json:"replicas,omitempty"`
	Storage               *ClustersclusterIdStorage            `json:"storage,omitempty"`
}

func (m ClustersClusterIdBody1) String() string {
	data, _ := json.MarshalIndent(m, "", "\t")
	return string(data)
}
