name: conventional-commits

on:
  pull_request:

jobs:
  commit-compliance:
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v3.5.1
        with:
          fetch-depth: '0'

      # Verify conventional commit compliance
      - name: Verify conventional commit compliance
        uses: docker://aevea/commitsar
