name: spellcheck-woke
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:

  # Check code for non-inclusive language
  woke:
    name: Run woke
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: woke
        uses: get-woke/woke-action@v0
        with:
          # Cause the check to fail on any broke rules
          fail-on-error: true

  # Enforce en-us spell check
  spellcheck:
    name: Run spellcheck
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Spellcheck
        uses: rojopolis/spellcheck-github-actions@0.36.0
