name: "Test"

# Run this workflow every time a new commit pushed to your repository
on: push

env:
  GOLANG_VERSION: "1.21.x"

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest,  macOS-latest ]

    name: test code base
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0

      - name: Configure Git for private modules
        shell: bash
        env:
          GITHUB_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
        run: git config --global url."https://x:${GITHUB_API_TOKEN}@github.com".insteadOf "https://github.com"

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GOLANG_VERSION }}

      - name: Run unit tests
        run: go test -p=1 -v ./...
